version: "3"

services:
  db-mysql:
    container_name: wanted_board_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "4000:3306"
    networks:
      - wanted_network

  spring-app:
    container_name: board_spring_app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db-mysql
    networks:
      - wanted_network
networks:
  wanted_network: